Areas/SonicStore/Controllers/CustomerContactManage/DetailCustomerContactController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using SonicStore.Areas.SonicStore.Models;

namespace SonicStore.Areas.SonicStore.Controllers.CustomerContactManage
{
    [Area("SonicStore")]
    [Authorize(Roles = "sale")]
    public class DetailCustomerContactController : Controller
    {
        private readonly SonicStoreContext _context;

        public DetailCustomerContactController()
        {
            _context = new SonicStoreContext();
        }


        [Route("/contact-detail/{id?}")]
        public async Task<IActionResult> DetailCustomerContactScreen(int id)
        {
            var cus = await (from u in _context.Users
                             join a in _context.Accounts
                             on u.AccountId equals a.Id
                             where u.RoleId == 1 && u.Id == id
                             select new
                             {
                                 AccId = a.Id,
                                 Id = u.Id,
                                 FullName = u.FullName,
                                 Dob = u.Dob,
                                 Email = u.Email,
                                 Phone = u.Phone,
                                 Gender = u.Gender,
                                 UpdateDate = u.UpdateDate,
                                 UpdateBy = u.UpdateBy,
                                 Status = a.Status
                             }).FirstOrDefaultAsync();

            var adds = await _context.UserAddresses.Where(u => u.UserId == id).ToListAsync();
            var checkout = await (from od in _context.OrderDetails
                                  join sto in _context.Storages
                                  on od.StorageId equals sto.Id
                                  join pr in _context.Products
                                  on sto.ProductId equals pr.Id
                                  where od.CustomerId == id && od.Status.Equals("bill")
                                  select new
                                  {
                                      name = pr.Name,
                                      num = od.Quantity,
                                      storage = sto.Storage_capacity,
                                      price = od.Price


                                  }).ToListAsync();
            ViewBag.cus = cus;
            ViewBag.adds = adds;
            ViewBag.checks = checkout;

            return View();
        }
        [HttpPost("/change/{id}")]
        public async Task<IActionResult> changeStatusAccount(int id)
        {

            var acc = await _context.Accounts.Where(u => u.Id == id).FirstOrDefaultAsync();
            var user = _context.Users.FirstOrDefault(u => u.AccountId == acc.Id);
            string name = user.FullName;
            if (acc != null)
            {
                if (acc.Status.Equals("on"))
                {
                    acc.Status = "off";
                    TempData["Message"] = $"Đã khóa tài khoản của {name}";

                }
                else
                {
                    acc.Status = "on";
                    TempData["Message"] = $"Đã mở tài khoản của {name}";

                }
                _context.SaveChanges();

            }
            return RedirectToAction("CustomerContact", "CustomerContact", new { area = "SonicStore" });
        }
    }
}

Areas/SonicStore/Views/DetailCustomerContact/DetailCustomerContactScreen.cshtml
@{
    Layout = "_LayoutSale";
    var cus = ViewBag.cus;
    var adds = ViewBag.adds;
    var checkout = ViewBag.checks;
}
<div>
    @*  @if (cus.Status.Equals("off"))
    {

    <form asp-controller="DetailCustomerContact" asp-action="changeStatusAccount" asp-route-id="@cus.AccId">
    <button type="submit" class=" btn btn-success rounded-pill" onclick="return myFunction()">
    Mở Khóa
    </button>
    </form>
    }
    else
    {
    <form asp-controller="DetailCustomerContact" asp-action="changeStatusAccount" asp-route-id="@cus.AccId">

    <button type="submit" class="  btn btn-danger rounded-pill" onclick="return myFunction()">
    Khóa tài khoản
    </button>
    </form>

    } *@
</div>
<div style="">
    <h5>Thông tin khách hàng</h5>
    <table class="table table-bordered" style="width:100%;text-align:center;box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2); background-color:#ffffff;border-radius:10px">
        <thead>
            <tr>
                <th>ID</th>
                <th>Họ tên</th>
                <th>Ngày sinh</th>
                <th>Email</th>
                <th>Số điện thoại</th>
                <th>Giới tính</th>
                <th>Ngày tham gia</th>
                <th>Trạng thái</th>
            </tr>
        </thead>
        <tr>
            <td>@cus.Id</td>
            <td>@cus.FullName</td>
            <td>@cus.Dob</td>
            @{
                string mail = "mailto:" + @cus.Email;
            }
            <td><a href="@mail">@cus.Email</a></td>
            <td>@cus.Phone</td>
            @if (cus.Gender.Equals("true", StringComparison.OrdinalIgnoreCase))
            {
                <th><div class="badge bg-info text-white rounded-pill">Nam</div></th>
            }
            else
            {
                <th><div class="badge bg-primary text-white rounded-pill">Nữ</div></th>
            }
            <td>@cus.UpdateDate</td>

            @if (cus.Status.Equals("off"))
            {
                <td>
                    <div class="badge text-while bg-danger rounded-pill">
                        Khóa
                    </div>
                </td>
            }
            else
            {
                <td>
                    <div class="badge text-white bg-success rounded-pill">
                        Bình thường
                    </div>
                </td>
            }


        </tr>
    </table>
</div>
<div style="">
    <h5>Địa chỉ khách hàng</h5>
    <table class="table table-bordered" style="width:100%;text-align:left;box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2); background-color:#ffffff;border-radius:10px">


        @foreach (var i in adds)
        {
            <tr>
                <td>
                    @if (i.Status)
                    {
                        <p><div class="badge bg-primary text-white rounded-pill">(Măc định)</div> @i.User_Address</p>
                    }
                    else
                    {
                        @i.User_Address
                    }
                </td>

            </tr>
        }

    </table>
</div>

<div style="">
    <h5>Những đơn hàng đã thanh toán</h5>
    <table class="table table-bordered" style="width:100%;text-align:left;box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2); background-color:#ffffff;border-radius:10px">

        <thead>
            <tr>
                <th>Tên sản phẩm</th>
                <th>Số lượng</th>
                <th>Bộ nhớ</th>
                <th>Giá cả</th>
            </tr>
        </thead>
        @foreach (var check in checkout)
        {
            <tr>
                <td>@check.name</td>
                <td>@check.num</td>
                <td>@check.storage</td>
                <td class="js-format-price" data-price="@check.price">@check.price</td>
            </tr>

        }


    </table>
</div>
<script>
    document.addEventListener("DOMContentLoaded", () => {
        var formatter = new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' });
        var priceTags = document.querySelectorAll('.js-format-price');
        priceTags.forEach(tag => {
            var price = tag.getAttribute('data-price');
            var formattedPrice = formatter.format(price);
            tag.textContent = formattedPrice;
        });

        var saleTags = document.querySelectorAll('.ex_pricesale');
        saleTags.forEach(tag => {
            var price = parseFloat(tag.getAttribute('data-price'));
            var originalPrice = parseFloat(tag.getAttribute('data-price1'));
            var discountPercent = ((originalPrice - price) / originalPrice) * 100;
            var roundedDiscountPercent = Math.round(discountPercent);
            tag.textContent = roundedDiscountPercent + '%';
        });
        // Hiển thị thông báo nếu có
        var statusMessage = "@TempData["Message"]";
        if (statusMessage) {
            alert(statusMessage);
        }
    })
</script>
<script>
    sessionStorage.setItem('previousPageProfile', window.location.href);
    var statusMessage = @Html.Raw(Json.Serialize(@TempData["Message"]));
    if (statusMessage) {
        alert(statusMessage);
    }
    function myFunction() {
        let text = "Bạn có muốn thay đổi không!";
        if (confirm(text)) {
            // User confirmed, submit the form
            document.getElementById('editForm').submit();
            return true;
        } else {
            // User canceled, prevent form submission
            return false;
        }

    }
</script>