Areas/SonicStore/Controllers/TechNewsListManage/EditNewsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SonicStore.Areas.SonicStore.Models;
using System.IO;
using System.Threading.Tasks;

namespace SonicStore.Areas.SonicStore.Controllers.TechNewsListManage
{
    [Area("SonicStore")]
    [Authorize(Roles = "marketing")]
    public class EditNewsController : Controller
    {
        private readonly SonicStoreContext _context;
        public EditNewsController(SonicStoreContext context)
        {
            _context = context;
        }

        [Route("edit-news/{id}")]
        public async Task<IActionResult> EditNewsScreen(int id)
        {
            var news = await _context.ProductNews.FindAsync(id);
            ViewBag.News = news;
            ViewBag.ImageFileName = news?.ImageThumbnail != null ? Path.GetFileName(news.ImageThumbnail) : "";
            return View("EditNewsScreen");
        }

        [HttpPost("edit-tech-news")]
        public async Task<IActionResult> EditTechNews([FromForm] ProductNews productNews, [FromForm] string ImageFileName, [FromForm] int Id)
        {
            var userJson = HttpContext.Session.GetString("user");
            User user = null;
            if (!string.IsNullOrEmpty(userJson))
            {
                user = JsonConvert.DeserializeObject<User>(userJson);
            }
            int userId = user.Id;

            if (productNews != null)
            {
                var existingNews = await _context.ProductNews.FindAsync(Id);
                if (existingNews != null)
                {
                    existingNews.Title = productNews.Title;
                    if (!string.IsNullOrEmpty(ImageFileName))
                    {
                        existingNews.ImageThumbnail = "images/tech_news/" + ImageFileName;
                    }
                    existingNews.UpdateAt = DateTime.Now;
                    existingNews.UpdateBy = userId;
                    existingNews.Status = true;
                    existingNews.Content = productNews.Content;

                    await _context.SaveChangesAsync();
                }
            }

            return Redirect("https://localhost:44390/tech-news-list");
        }
    }
}

Areas/SonicStore/Views/EditNews/EditNewsScreen.cshtml
@{
    ViewData["Title"] = "EditTechNews";
    Layout = null;
    var news = ViewBag.News;
    var imageFileName = ViewBag.ImageFileName;
}




<title>Posts List - SB Admin Pro</title>

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css"
      rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/lang/summernote-ko-KR.min.js"></script>
<link rel="icon" type="image/png" href="images/icons/favicon.ico" />
<link rel="stylesheet"
      type="text/css"
      href="https://colorlib.com/etc/cf/ContactFrom_v1/vendor/bootstrap/css/bootstrap.min.css" />
<link rel="stylesheet"
      type="text/css"
      href="https://colorlib.com/etc/cf/ContactFrom_v1/vendor/animate/animate.css" />
<link rel="stylesheet"
      type="text/css"
      href="https://colorlib.com/etc/cf/ContactFrom_v1/vendor/css-hamburgers/hamburgers.min.css" />
<link rel="stylesheet"
      type="text/css"
      href="https://colorlib.com/etc/cf/ContactFrom_v1/vendor/select2/select2.min.css" />
<link rel="stylesheet"
      type="text/css"
      href="https://colorlib.com/etc/cf/ContactFrom_v1/css/util.css" />
<link rel="stylesheet"
      type="text/css"
      href="https://colorlib.com/etc/cf/ContactFrom_v1/css/main.css" />

<style>
    .container-contact1 {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh; /* Full viewport height */
        width: 100vw; /* Full viewport width */
        position: fixed; /* Fix position relative to viewport */
        top: 0;
        left: 0;
    }

    .bg-white {
        background-color: #e81500 !important;
    }

    .file-input-wrapper {
        position: relative;
        overflow: hidden;
        display: inline-block;
    }

    .file-input {
        font-size: 1rem;
        font-weight: 700;
        color: white;
        background-color: #4caf50;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }

        .file-input:hover {
            background-color: #45a049;
        }

    .btn-submit {
        background-color: green;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

        .btn-submit:hover {
            background-color: darkgreen;
        }

    .file-name {
        margin-left: 15px;
        font-size: 1rem;
        font-weight: 400;
        vertical-align: middle;
    }

    .flex-container {
        display: flex;
        align-items: center;
    }

        .flex-container h6 {
            margin: 0 10px 0 0;
        }

    .wrap-input1 {
        width: 100%;
        box-sizing: border-box;
    }

    .input1 {
        width: 100%;
        box-sizing: border-box;
    }

    .note-editor {
        width: 100%;
        box-sizing: border-box;
    }
</style>

<meta name="robots" content="noindex, follow" />
<div class="">
    <div class="container-contact1">
        <form asp-controller="EditNews"
              asp-action="EditTechNews"
              method="post"
              id="myForm"
              enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-12"
                     style="
            display: flex;
            flex-direction: column;
            justify-content: center;
          ">
                    <div>
                        <span class="contact1-form-title">Chỉnh sửa bài viết</span>
                        <input type="hidden" name="Id" value="@news.Id" />
                        <div class="wrap-input1 validate-input" style="width: 100%">
                            <input class="input1"
                                   type="text"
                                   name="productNews.Title"
                                   value="@news.Title"
                                   required />
                            <span class="shadow-input1"></span>
                        </div>

                        <div class="wrap-input1 validate-input" style="width: 100%; display: flex; align-items: center">
                            <div class="wrap-input1 validate-input" style="width: 100%; display: flex; align-items: center">
                                <input type="file" id="fileUpload" name="productNews.ImageThumbnail" />
                                <span class="shadow-input1"></span>
                            </div>
                            
                        </div>

                        <div class="wrap-input1 validate-input" style="width: 100%"
                             data-validate="Subject is required">

                            <textarea class="input1"
                                      id="summernote"
                                      name="productNews.Content">@news.Content</textarea>
                            <span class="shadow-input1"></span>
                        </div>

                        <input type="hidden" id="imageFileName" name="ImageFileName" />
                        <div style="text-align: center; margin-top: 20px;">
                            <button type="submit" class="btn-submit">Xác nhận</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>



</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script src="https://colorlib.com/etc/cf/ContactFrom_v1/vendor/jquery/jquery-3.2.1.min.js"></script>

<script src="https://colorlib.com/etc/cf/ContactFrom_v1/vendor/bootstrap/js/popper.js"></script>
<script src="https://colorlib.com/etc/cf/ContactFrom_v1/vendor/bootstrap/js/bootstrap.min.js"></script>

<script src="https://colorlib.com/etc/cf/ContactFrom_v1/vendor/select2/select2.min.js"></script>

<script src="https://colorlib.com/etc/cf/ContactFrom_v1/vendor/tilt/tilt.jquery.min.js"></script>
<script>
    $(".js-tilt").tilt({
        scale: 1.1,
    });
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-bs4.min.js"></script>
<script async
        src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
        dataLayer.push(arguments);
    }
    gtag("js", new Date());

    gtag("config", "UA-23581568-13");
</script>
<script>
    $(document).ready(function () {
        $("#summernote").summernote({
            placeholder: "Chi tiết bài viết",
            tabsize: 4.5,
            height: 300,
            width: "100%",
        });

        document
            .getElementById("fileUpload")
            .addEventListener("change", function () {
                var fileName = this.files[0].name;
                document.getElementById("fileName").textContent = fileName;
            });
    });
</script>
<script src="https://colorlib.com/etc/cf/ContactFrom_v1/js/main.js"></script>
<script type="text/javascript">
    $(function () {
        // index page card list
        if ($('.card-list').length) {
            var $cardArrow = $('.card-arrow');
            var $cardListInner = $('.card-list-inner');

            $cardListInner.scroll(function () {
                $cardArrow.addClass('disappear');
                if ($cardListInner.scrollLeft() < 20) {
                    $cardArrow.removeClass('disappear');
                }
            });
        }

        // main summernote with custom placeholder
        var $placeholder = $('.placeholder');
        $('#summernote').summernote({
            height: 300,
            codemirror: {
                mode: 'text/html',
                htmlMode: true,
                lineNumbers: true,
                theme: 'monokai'
            },
            callbacks: {
                onInit: function () {
                    $placeholder.show();
                },
                onFocus: function () {
                    $placeholder.hide();
                },
                onBlur: function () {
                    var $self = $(this);
                    setTimeout(function () {
                        if ($self.summernote('isEmpty') && !$self.summernote('codeview.isActivated')) {
                            $placeholder.show();
                        }
                    }, 300);
                }
            }
        });
    });
</script>

    </div>


<p>
    Summernote v0.8.18 · Created and Maintained by <a href="https://github.com/summernote">Summernote team</a>.<br>Based on <a href="http://getbootstrap.com">Bootstrap</a> and <a href="http://jquery.com">jQuery</a>.<br>Summernote distributed under the MIT license.
</p>
<p><a href="https://github.com/summernote/summernote">GitHub Project</a> · <a href="https://github.com/summernote/summernote/issues">Issues</a> · <a href="https://communityinviter.com/apps/summernote/summernote">Slack</a> · <a href="https://stackoverflow.com/search?q=summernote">Stackoverflow</a></p>

<script>
    document.getElementById('myForm').addEventListener('submit', function (event) {
        var fileInput = document.getElementById('fileUpload');
        var fileName = fileInput.files[0].name;
        document.getElementById('imageFileName').value = fileName;
    });
</script>
<script>
    if (localStorage && localStorage.getItem && localStorage.getItem('github_expire') && localStorage.getItem('github_expire') > (new Date()).getTime()) {
        $('.github').text((+localStorage.getItem('github_star')).toLocaleString());
    } else {
        $.getJSON('https://api.github.com/repos/summernote/summernote', function (d) {
            if (localStorage && localStorage.setItem) {
                localStorage.setItem('github_star', d.stargazers_count);
                localStorage.setItem('github_expire', (new Date()).getTime() + (10 * 60 * 1000)/*10 mins*/);
            }
            $('.github').text(d.stargazers_count.toLocaleString());
        }).fail(function () {
            if (localStorage && localStorage.getItem && localStorage.getItem('github_star')) {
                $('.github').text(localStorage.getItem('github_star').toLocaleString());
            }
        });
    }
</script>